kafka:
  consumer:
    tripstart:
        bootstrap: ubuntu-lab:9092
        group: TripStartListener
        topic: tripstart
    tripend:
        bootstrap: ubuntu-lab:9092
        group: TripEndListener
        topic: tripend

management:
  security:
    enabled: false